name: Change shell
on: push
# shellキーを指定してないと、パイプエラーに気づかない
defaults:
  run:
    shell: bash
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "${SHELL}"
      - shell: python
        run: |
          import os
          print(os.environ['PATH'])
